version: "3"

services:
  couchbase:
    image: registry.conci.info/conci/image/couchbase:master
    networks:
      internal:
        aliases:
          - couchbase
    ports:
       - "8091:8091"
  php1:
    image: registry.conci.info/conci/image/base:master
    networks:
      - internal
    depends_on:
      - couchbase
    tty: true
    volumes:
      - ".:/opt/conci"
  php2:
      image: registry.conci.info/conci/image/base:master
      networks:
        - internal
      depends_on:
        - couchbase
      tty: true
      volumes:
        - ".:/opt/conci"
  php3:
      image: registry.conci.info/conci/image/base:master
      networks:
        - internal
      depends_on:
        - couchbase
      tty: true
      volumes:
        - ".:/opt/conci"
  php4:
      image: registry.conci.info/conci/image/base:master
      networks:
        - internal
      depends_on:
        - couchbase
      tty: true
      volumes:
        - ".:/opt/conci"
  php5:
      image: registry.conci.info/conci/image/base:master
      networks:
        - internal
      depends_on:
        - couchbase
      tty: true
      volumes:
        - ".:/opt/conci"
networks:
  internal:
