version: "3"

services:
  couchbase:
    image: registry.conci.info/conci/image/couchbase:master
    networks:
      internal:
        aliases:
          - couchbase
    ports:
       - "8091:8091"
  php:
    image: registry.conci.info/conci/image/base:master
    networks:
      - internal
    depends_on:
      - couchbase
    tty: true
    volumes:
      - ".:/opt/conci"
networks:
  internal:
